export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
export const BIG_SCREEN_STATUS_CHANGE = "BIG_SCREEN_STATUS_CHANGE";
export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const LOGIN_STATUS_CHANGED = "LOGIN_STATUS_CHANGED";
export const TOKEN_CHANGED = "TOKEN_CHANGED";
