export const productSchema = [
  {
    id: 0,
    category: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 1,
    subCategory: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 2,
    title: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 3,
    definition: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 4,
    productImageUrl: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 5,
    stockCount: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 6,
    specifications: [],
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 7,
    price: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 8,
    priceDecimal: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 9,
    discountPercent: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 10,
    warranty: false,
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
  {
    id: 11,
    warrantyExplanation: "",
    message: "",
    question: "",
    success: false,
    errorMsg: "",
    isError: false,
    explanation: "",
  },
];
